zuul:
    routes:
        friend-service:
            path: /friend-service/**
            retryable: true
            service-id: friend-service
        party-service:
            path: /party-service/**
            retryable: true
            service-id: party-service

friend-service:
    ribbon:
        NIWSServerListClassName: io.fabric8.kubeflix.ribbon.KubernetesServerList
        KubernetesNamespace: ${k8sNAMESPACE}
        PortName: tcp80

party-service:
    ribbon:
        NIWSServerListClassName: io.fabric8.kubeflix.ribbon.KubernetesServerList
        KubernetesNamespace: ${k8sNAMESPACE}
        PortName: tcp80


ribbon:
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  ReadTimeout: ${RIBBON_TIMEOUT:2000}

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: ${HYSTRIX_TIMEOUT:2000}        
