apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: mongodb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: mongodb
      name: mongodb
    spec:
      containers:
      - image: mongo:3.6
        imagePullPolicy: Always
        name: mongodb
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: mongodb
  name: mongodb
spec:
  ports:
  - name: tcp-27017-27017-m7vcp
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    k8s-app: mongodb
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
