kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: gr8t-parties-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "endpoints", "services"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: gr8t-parties-role-binding
subjects:
- kind: ServiceAccount
  name: edge-service
- kind: ServiceAccount
  name: party-service
roleRef:
  kind: Role
  name: gr8t-parties-role
  apiGroup: rbac.authorization.k8s.io
